# Generated by Django 4.0.1 on 2022-02-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pots', '0003_alter_pot_height_cm_alter_pot_width_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.pot')),
            ],
        ),
    ]
