# Generated by Django 4.0.1 on 2022-01-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='small_print',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
