# Generated by Django 4.0.1 on 2022-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0002_pot_small_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='pot',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
